// app/layout.tsx
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import MiniKitProvider from "@/components/minikit-provider";
import ClientErudaProvider from "@/providers/ClientErudaProvider";
import NextAuthProvider from "@/components/next-auth-provider";
import ClientOnlyRedirect from "@/components/OnboardingRedirect/ClientOnlyRedirect";
import ClientLayout from "@/components/ClientLayout"; // Import ClientLayout

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} overflow-hidden`}>
        <NextAuthProvider>
          <ClientOnlyRedirect>
            <ClientErudaProvider>
              <MiniKitProvider>
                <ClientLayout>{children}</ClientLayout>{" "}
                {/* Wrap children in ClientLayout */}
              </MiniKitProvider>
            </ClientErudaProvider>
          </ClientOnlyRedirect>
        </NextAuthProvider>
      </body>
    </html>
  );
}
